### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by thisischrys** [TehNut-Mods/Soul-Shards-The-Old-Ways#58]
#### Issue Description:
https://openeye.openmods.info/crashes/aaaef5e8292be2cdd6cac01013e8f4ed
can provide server crashlog if needed

Openeye seems to think it's this mod, though I also see Astral Sorcery mentioned in there?
#### What happens:
server crash when someone comes near a certain area

#### What you expected to happen:
not crashing

#### Steps to reproduce:

1. go there
2. 
3. 
...

____
#### Affected Versions (Do *not* use "latest"):

- Soul Shards: 1.12-2.7.5-55
- Minecraft: 1.12.2
- Forge: 14.23.2.2624

**Comment by thisischrys** [comment]
This happened the next time this person logged in after we updated to 5-55 btw

**Comment by thisischrys** [comment]
Can confirm downgrading fixed it

**Comment by Rixxaw** [comment]
A better description of this problem, which I and several others in the Forever Stranded LS discord have all had.  If you place a grinder from Astral Sorcery down on the ground and log off / back on the world won't load.  If you also have Soul Shards TOW version 2.7.5-55.

If you downgrade to 2.7.5-53 the world loads.

Crash Log from my game crashing with Grinder + .55 load.

[https://pastebin.com/EufsZRc3](url)

The tricky part is that it seems 5-55 was specifically released to address an issue with Spawner Controll which is also in this pack, and I have no idea what SS TOW or Spawner Control do, but in order to progress in Astral so I can complete my quests I have back-rev'ed SSTOW to .53.  I'm not sure if this is something everyone playing FS LS should do or if we should tell everyone to just not leave grinders on the ground.
